namespace: "ntheule_lab"
name: "pve_vm"
version: "1.0.0"
readme: "readme.md"
authors:
    - "Nathan Theule"
dependencies:
  community.general: "*"
repository: "https://github.com/ntheule/ansible-pve-vm"
